name: Publish Packages

on: [push]
  
jobs:
  build:
  
    runs-on: ubuntu-latest
      
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.1
    - name: Build with dotnet
      run: dotnet build --configuration Release
    - name: Run ls
      run: ls 
    - name: Pack with dotnet
      run: dotnet pack ./Narojay.Tools.Core.csproj --output nuget-packages --configuration Release
    - name: Run ls
      run: ls 
    - name: Push with dotnet
      run: dotnet nuget push ./nuget-packages/*.nupkg --api-key ${{ secrets.NUGET_KEY }} --source https://api.nuget.org/v3/index.json

