name: Publish Packages

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
      
    - name: publish nuget package
      uses: dansiegel/publish-nuget@2
      with:
       filename: '*.nupkg'
       apiKey: ${{secrets.NUGET_KEY}}
       feedUrl: 'https://api.nuget.org/v3/index.json'

